name: Atualizador de Lista IPTV

on:
  schedule:
    - cron: '0 3 * * *' # Executa diariamente às 00:00 (Brasília)
  workflow_dispatch:     # Permite rodar manualmente pelo botão

permissions:
  contents: write       # Garante permissão de escrita para salvar os arquivos

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Executar script gerador
        run: python atualizar_lista.py

      - name: Commit e Push das alterações
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add lista.m3u epg.xml epg.xml.gz
          git commit -m "Auto: lista e EPG atualizados com sucesso" || echo "Nenhuma alteração detectada"
          git push
